# Generated by Django 5.0.6 on 2026-04-07 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.UUIDField(unique=True)),
                ('url', models.URLField()),
                ('display_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upload_pending', 'Upload Pending'), ('active', 'Active'), ('aborted', 'Aborted'), ('deleted', 'Deleted')], default='upload_pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
