# Generated by Django 5.0.6 on 2026-04-14 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_domain_id_alter_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Jika True, tampil di katalog publik /templates/.'),
        ),
        migrations.AddField(
            model_name='template',
            name='source_tenant_schema',
            field=models.CharField(blank=True, db_index=True, help_text='Schema tenant yang membuat template ini. Null = template sistem.', max_length=63, null=True),
        ),
        migrations.CreateModel(
            name='TemplatePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_home', models.BooleanField(default=False, help_text='Tandai sebagai halaman utama template.')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.template')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='templatesection',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.templatepage'),
        ),
    ]
