import json
import requests
from django.conf import settings


class DeepSeekAdapter:
    """
    Minimal DeepSeek adapter.
    If API key/base URL are not configured, it returns deterministic fallback drafts
    so the rest of the pipeline can still be tested end-to-end.
    """

    def __init__(self):
        self.api_key = getattr(settings, 'DEEPSEEK_API_KEY', '')
        self.base_url = getattr(settings, 'DEEPSEEK_BASE_URL', 'https://api.deepseek.com')
        self.model = getattr(settings, 'DEEPSEEK_MODEL', 'deepseek-chat')
        self.vision_model = getattr(settings, 'DEEPSEEK_VISION_MODEL', '') or self.model

    def brainstorm_reply(self, messages, mode, llm_mode='chat_economy', llm_model=''):
        if not self.api_key:
            return (
                f"I collected your context for {mode} mode. "
                "When you are ready, click Generate to create structured drafts."
            )

        system_prompt = (
            'You are ArnaSite AI Copilot. Help users brainstorm website structure and content. '
            'Return concise guidance in English.'
        )

        if llm_mode == 'multimodal_vision':
            llm_messages = [{'role': 'system', 'content': system_prompt}] + messages
            return self._chat_text(
                llm_messages,
                model_override=llm_model or self.vision_model,
            )

        # Economy mode: flatten multimodal content to plain text.
        text_messages = []
        for m in messages:
            content = m.get('content', '')
            if isinstance(content, list):
                parts = []
                for c in content:
                    if c.get('type') == 'text':
                        parts.append(c.get('text', ''))
                    elif c.get('type') == 'image_url':
                        url = (c.get('image_url') or {}).get('url', '')
                        parts.append(f"[image-reference] {url}")
                content = '\n'.join(p for p in parts if p)
            text_messages.append({'role': m.get('role', 'user'), 'content': content})

        llm_messages = [{'role': 'system', 'content': system_prompt}] + text_messages
        return self._chat_text(
            llm_messages,
            model_override=llm_model or self.model,
        )

    def generate_template_draft(self, context_text):
        if not self.api_key:
            return {
                'name': 'AI Generated Business Template',
                'slug': 'ai-generated-business-template',
                'description': context_text[:500],
                'category': 'business',
                'preview_image_url': 'https://example.com/preview.jpg',
                'pages': [
                    {
                        'title': 'Home',
                        'slug': 'home',
                        'order': 1,
                        'is_home': True,
                        'sections': [
                            {
                                'type': 'hero',
                                'order': 1,
                                'is_active': True,
                                'blocks': [
                                    {
                                        'title': 'Welcome',
                                        'subtitle': 'Your trusted partner',
                                        'description': 'Generated hero copy.',
                                        'image_url': 'https://example.com/hero.jpg',
                                        'order': 1,
                                        'extra': {'cta_text': 'Get Started', 'cta_url': '/contact'},
                                        'items': [],
                                    }
                                ],
                            }
                        ],
                    }
                ],
                'extra_conventions': {
                    'hero': {
                        'cta_text': 'string',
                        'cta_url': 'string'
                    }
                },
            }

        prompt = (
            'Generate a valid JSON object for an ArnaSite template draft. '
            'Return JSON only with fields required by template.schema.json. '
            f'Context: {context_text}'
        )
        return self._chat_json(prompt, model_override=self.model)

    def generate_site_content_draft(self, context_text, template_id):
        if not self.api_key:
            return {
                'template_id': str(template_id),
                'pages': [
                    {
                        'slug': 'home',
                        'title': 'Home',
                        'is_home': True,
                        'is_active': True,
                        'meta_title': 'Home',
                        'meta_description': 'Generated by AI Copilot.',
                        'sections': [
                            {
                                'type': 'hero',
                                'order': 1,
                                'is_active': True,
                                'blocks': [
                                    {
                                        'order': 1,
                                        'title': 'Nusa Prima',
                                        'subtitle': 'Trusted Energy Partner',
                                        'description': 'Generated site content draft.',
                                        'image_url': 'https://example.com/hero-site.jpg',
                                        'extra': {'cta_text': 'Contact Us', 'cta_url': '/contact'},
                                        'items': [],
                                    }
                                ],
                            }
                        ],
                    }
                ],
            }

        prompt = (
            'Generate a valid JSON object for ArnaSite website content draft. '
            'Return JSON only with fields required by site-content.schema.json. '
            f'Template ID: {template_id}. Context: {context_text}'
        )
        return self._chat_json(prompt, model_override=self.model)

    def generate_fe_guide(self, template_payload):
        if not self.api_key:
            return {
                'title': f"Frontend Guide - {template_payload.get('name', 'Template')}",
                'summary': 'Implementation guide generated by AI Copilot.',
                'section_catalog': [
                    {
                        'type': 'hero',
                        'purpose': 'Top section for headline and primary CTA.',
                        'required_fields': ['title', 'subtitle', 'description'],
                        'optional_fields': ['image_url', 'extra.cta_text', 'extra.cta_url'],
                    }
                ],
                'component_mapping': [
                    {
                        'section_type': 'hero',
                        'component_name': 'HeroSection',
                        'props_contract': 'props.blocks[0] with title, subtitle, description, image_url, extra',
                    }
                ],
                'example_payload': template_payload,
                'implementation_notes': [
                    'Sort sections by order ascending.',
                    'Render only active sections.',
                    'Use responsive image sizing for hero visuals.',
                ],
                'markdown': '# Frontend Guide\n\nUse section.type mapping to render components.',
            }

        prompt = (
            'Generate a valid JSON object for FE guide. '
            'Return JSON only with fields required by fe-guide.schema.json. '
            f'Template payload: {json.dumps(template_payload)[:12000]}'
        )
        return self._chat_json(prompt, model_override=self.model)

    def _chat_text(self, messages, model_override=''):
        payload = {
            'model': model_override or self.model,
            'messages': messages,
            'temperature': 0.3,
        }
        resp = requests.post(
            f'{self.base_url}/v1/chat/completions',
            headers={
                'Authorization': f'Bearer {self.api_key}',
                'Content-Type': 'application/json',
            },
            json=payload,
            timeout=45,
        )
        resp.raise_for_status()
        data = resp.json()
        return data['choices'][0]['message']['content']

    def _chat_json(self, prompt, model_override=''):
        content = self._chat_text([
            {'role': 'system', 'content': 'Return JSON only.'},
            {'role': 'user', 'content': prompt},
        ], model_override=model_override)
        return json.loads(content)
